### ISSUE TITLE
Incorrect index in equation for classification help page

### ISSUE THREAD

**Issue by joey-kilgore** [Hippocampome-Org/php_v2#13]
The [help classification of firing patterns](https://hippocampome.org/php/Help_Principles_of_Classification_of_Firing_Pattern_Elements.php) page has an inccorect subscript for the TSTUT (1.1) inequality

**currently it shows:**
$ISI_i > Fpost*ISI_{i-1}$

**It should be:**
$ISI_i > Fpost*ISI_{i+1}$  `+1 instead of -1`  
and you can see this is correct by the java code that was originally used to implement this [here](https://github.com/Hippocampome-Org/Time/blob/716e243f764941cd64181bae8ad9c69c04f0c9b2/src/ec/app/izhikevich/evaluator/qualifier/SpikePatternClassifier.java#L310C1-L311C1)

I can't see how this page is stored in this repo. I'm assuming this is a just a static image that is stored on the server, so I'm not sure how this would be edited.
If it isn't possible to regenerate this image, there are 2 options:
1. Recreate this page in php directly instead of using an image  
2. add a note on the bottom of the php page noting this correction

see it ref'd twice in the code here:
https://github.com/Hippocampome-Org/php_v2/blob/cf8d53c25251dd945f1f7fbf94787b606eedcc8b/help.php#L78

https://github.com/Hippocampome-Org/php_v2/blob/cf8d53c25251dd945f1f7fbf94787b606eedcc8b/neuron_by_pattern.php#L187

**Comment by drdiek** [comment]
Joey,

Thank you for bringing this to our attention. We will look into it and will let you know what corrections we were able to make.

At this time, I cannot provide you with an estimate of when we will get around to addressing this. We are currently in the middle of switching host servers, and it is occupying most of our bandwidth.

Sincerely,

Diek

**Comment by drdiek** [comment]
Joey,

We have corrected the error. That was some impressive detective work to have flagged that minor error.

Sincerely,

Diek

**Comment by joey-kilgore** [comment]
Thanks! Quick fix, but where did you end up adding it? I didn't see any changes in the git history.

Also the website is now giving me a "Connection failed: No such file or directory" when trying to connect.

Please let me know if I can provide more information.
